spring:
    application:
      name: order-service
    zipkin:
      base-url: http://localhost:9411 
    enabled: false
    profiles: standalone
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 9002
    
zipkin:
  client:
   url: http://localhost:8082
    
hystrix:
  command:
    default : 
     execution:
       timeout: 
         enabled: false

logging:
 level:
   zipkin: debug
   org:
    springframework:
     web:
      client: info
management:
 security:
  enabled:  false   